const GET_JUGADORES = "GET_JUGADORES";
const GET_JUGADOR_BY_ID = "GET_JUGADOR_BY_ID";
const GET_JUGADOR_BY_NOMBRE = "GET_JUGADOR_BY_NOMBRE";
const POST_JUGADOR = "POST_JUGADOR";
const ERROR = "ERROR";


export {
    GET_JUGADORES,
    GET_JUGADOR_BY_ID,
    GET_JUGADOR_BY_NOMBRE,
    POST_JUGADOR,
    ERROR
};
